<a href="https://colab.research.google.com/github/nureeee/python-basic/blob/python/210601_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.rand(3, 4)

array([[0.4654068 , 0.47519356, 0.74012061, 0.70158791],
       [0.8263215 , 0.96808276, 0.77158156, 0.87156169],
       [0.09002669, 0.70678591, 0.73027538, 0.28639014]])

In [3]:
np.random.randn(2, 2, 3)

array([[[-0.07173388, -1.61035986, -1.43481162],
        [-0.70065768, -0.30076553,  0.04706464]],

       [[ 0.89554122,  0.62872836, -1.29428583],
        [-0.52735452, -1.17475735, -0.80311669]]])

In [4]:
np.random.uniform(1, 3, size=(2, 3))

array([[2.71593113, 2.49197423, 1.65897637],
       [2.00890489, 2.9987255 , 2.91648795]])

In [5]:
np.random.choice(10, size=(2, 3))

array([[8, 3, 6],
       [6, 1, 4]])

In [7]:
arr = np.arange(1, 25).reshape(4, 2, 3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [11]:
np.max(arr, axis=1)

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])

In [12]:
arr = np.random.randint(1, 25, size=(2, 2, 3, 2))
arr

array([[[[23, 16],
         [ 6, 13],
         [18, 19]],

        [[17,  6],
         [18, 14],
         [ 9, 12]]],


       [[[23, 17],
         [11,  8],
         [10,  1]],

        [[21, 18],
         [16, 17],
         [12, 16]]]])

In [17]:
np.min(arr, axis=1)

array([[[17,  6],
        [ 6, 13],
        [ 9, 12]],

       [[21, 17],
        [11,  8],
        [10,  1]]])

In [18]:
np.min(arr, axis=0)

array([[[23, 16],
        [ 6,  8],
        [10,  1]],

       [[17,  6],
        [16, 14],
        [ 9, 12]]])

In [19]:
np.min(arr, axis=2)

array([[[ 6, 13],
        [ 9,  6]],

       [[10,  1],
        [12, 16]]])

In [20]:
np.min(arr, axis=3)

array([[[16,  6, 18],
        [ 6, 14,  9]],

       [[17,  8,  1],
        [18, 16, 12]]])

In [21]:
import numpy as np

arr = np.array([[1, 2],
              [3, 4]], dtype=int)

new_arr = arr[:, np.newaxis]

print(arr)

print(new_arr)
print(new_arr[1][0])
print(new_arr[1][0][1])

[[1 2]
 [3 4]]
[[[1 2]]

 [[3 4]]]
[3 4]
4


In [22]:
new_arr

array([[[1, 2]],

       [[3, 4]]])

In [24]:
new_arr.ndim

3